<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.daviipkp.dothat</groupId> 
  <artifactId>dothat</artifactId> 
  <version>1.0</version>

  <name>DoThat</name>
  <url>https://dothat.satusbr.com</url> 

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>25</maven.compiler.source>
    <maven.compiler.target>25</maven.compiler.target>
  </properties>

  <repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

  <dependencies>
    <dependency>
	    <groupId>com.github.Daviiipkp</groupId>
	    <artifactId>DavieLib</artifactId>
	    <version>b3c1e76bd5</version>
	</dependency> 
  <dependency>
	    <groupId>com.github.Daviiipkp</groupId>
	    <artifactId>Textrie</artifactId>
	    <version>ccc7476709</version>
	</dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
      </plugin>
    </plugins>
  </build>
</project>
